name: .NET
defaults:
  run:
    working-directory: src/
    
on:
  pull_request:
    branches: 
    - "main"
    paths:
    - "src/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~Tests.Unit
